//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace text2jsonEnglishWords.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("text2jsonEnglishWords.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 第38期/群，团体，组/group
        ///第38期/发明物/invention
        ///第38期/以……告终/end up
        ///第38期/想法/mind
        ///第38期/放弃/give up
        ///第38期/吹/blow
        ///第38期/创立，设立/set up
        ///第38期/到达/arrive
        ///第38期/出现/appear
        ///第38期/中心，中央/center
        ///第38期/量；数量/amount
        ///第38期/集中（精力）/focus
        ///第38期/疾病/sickness
        ///第38期/健康的，结实的/fit
        ///第36-37期/笑/laugh
        ///第36-37期/相信/believe
        ///第36-37期/可能/probably
        ///第36-37期/摇晃/shake
        ///第36-37期/承诺/promise
        ///第36-37期/挥动，摇荡，前后摆动/swing
        ///第36-37期/空间/space
        ///第36-37期/错误/mistake
        ///第36-37期/解决/solve
        ///第36-37期/决定/decide
        ///第36-37期/有魔力的/magic
        ///第36-37期/逃跑/escape
        ///第36-37期/勇敢的/brave
        ///第36-37期/洞/ho [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string _72external {
            get {
                return ResourceManager.GetString("_72external", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 M12/西方传统音乐/traditional western music
        ///M12/奥地利首都/the capital of Austria
        ///M12/流经/go through
        ///M12/听着绝妙的嗓音/listen to the fantastic voice
        ///M12/摇滚乐迷/a fan of rock music
        ///M12/饶了我们吧(得了吧,让我们清静会吧)/give us a break
        ///M12/太快/沉/much too fast/heavy
        ///M12/太多工作/水/too much work/water
        ///M12/不太了解/非常了解/know little/much about
        ///M12/欧洲古典音乐的中心/the center of European classical music
        ///M12/带…周游/take sb. around
        ///M12/开音乐会/give concerts
        ///M12/几百部动听的音乐作品/hundreds of wonderful pieces of music
        ///M12/在…早年间/at an early age
        ///M12/发表,出版/come out
        ///M12 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string M12 {
            get {
                return ResourceManager.GetString("M12", resourceCulture);
            }
        }
    }
}
