//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace text2jsonEnglishWords.Properties {
  /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("text2jsonEnglishWords.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 第38期/群，团体，组/group
        ///第38期/发明物/invention
        ///第38期/以……告终/end up
        ///第38期/想法/mind
        ///第38期/放弃/give up
        ///第38期/吹/blow
        ///第38期/创立，设立/set up
        ///第38期/到达/arrive
        ///第38期/出现/appear
        ///第38期/中心，中央/center
        ///第38期/量；数量/amount
        ///第38期/集中（精力）/focus
        ///第38期/疾病/sickness
        ///第38期/健康的，结实的/fit
        ///第36-37期/笑/laugh
        ///第36-37期/相信/believe
        ///第36-37期/可能/probably
        ///第36-37期/摇晃/shake
        ///第36-37期/承诺/promise
        ///第36-37期/挥动，摇荡，前后摆动/swing
        ///第36-37期/空间/space
        ///第36-37期/错误/mistake
        ///第36-37期/解决/solve
        ///第36-37期/决定/decide
        ///第36-37期/有魔力的/magic
        ///第36-37期/逃跑/escape
        ///第36-37期/勇敢的/brave
        ///第36-37期/洞/ho [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string _72external {
            get {
                return ResourceManager.GetString("_72external", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Module 1/pair/n.（相关的）两个人， 一对/[pεə]
        ///Module 1/correct/v. 改正；纠正; adj. 正确的；对的/[kə&apos;rekt]
        ///Module 1/spelling/n. 拼写/[&apos;speliŋ]
        ///Module 1/word/n. 词；单词；字/[wə:d]
        ///Module 1/practise/v. 练习/[&apos;præktis]
        ///Module 1/match/v.找到与……相配之物，使相配；使成对/[mætʃ]
        ///Module 1/meaning/n. 意义；意思/[&apos;mi:niŋ]
        ///Module 1/complete/v.把……填完整；使完全/[kəm&apos;pli:t]
        ///Module 1/sentence/n. 句子/[&apos;sentəns]
        ///Module 1/dictionary/n. 词典；字典/[&apos;dikʃənəri]
        ///Module 1/grammar/n. 语法/[&apos;ɡræmə]
        ///Module 1/letter/n. 字母/[&apos;letə]
        ///Module 1/look up/查，查找/
        ///Module 1/mistake/n. 错误；过错/[mi&apos;st [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string _8_1 {
            get {
                return ResourceManager.GetString("_8_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 module  1/smell/v.有......的气味；闻；闻出  n.气味/
        ///module  1/soft/ adj. 软的；柔软的/
        ///module  1/sour/ adj. 酸的；馊的/
        ///module  1/cookie/  n.小甜饼；曲奇饼/
        ///module  1/pizza/ n. 比萨饼 /
        ///module  1/lovely/ adj. 令人愉快的；可爱的/
        ///module  1/done/ adj. 做完的/
        ///module  1/try/n. 尝试；努力/
        ///module  1/have a try/尝一尝；试试看/
        ///module  1/pie/n. 馅饼；派 /
        ///module  1/sound/v.听起来；令人觉得/
        ///module  1/sweet tooth/ 对甜食的爱好/
        ///module  1/salt/ n.盐；食盐/
        ///module  1/jam/ n.果酱 /
        ///module  1/for/prep. 用于；（表示持续的时间）达，计/
        ///module  1/favorite/ n. 最喜欢的人或事/
        ///module  1/ear/  n.耳朵 /
        ///module [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string _8_2 {
            get {
                return ResourceManager.GetString("_8_2", resourceCulture);
            }
        }
    }
}
